### ISSUE TITLE
British English

### ISSUE THREAD

**Issue by MrBrain295** [mdn/fetch-examples#27]
Some examples use British English but when #25 is merged it will use the United States English value for the `lang` attribute.

**Comment by teoli2003** [comment]
This is not a problem.

**Comment by MrBrain295** [comment]
@teoli2003 would it be ok if I worked on it?

**Comment by teoli2003** [comment]
I pushed a commit in #25 to mark the page as "en" and no more "en-US", so the problem is solved.
