### ISSUE TITLE
onrequestprogress do not work on POST uploads

### ISSUE THREAD

**Issue by glococo** [mdn/fetch-examples#8]
Hi,
I found no way of observing the progress on Upload fetch()

var garbage = new Float64Array(new ArrayBuffer(104856))
for (let i=0; i<garbage.length; i++) garbage[i] = Math.random()
var gArray    = []
for (let i=0; i<100; i++) gArray.push(garbage);
var gBlob = new Blob(gArray)

var controller = new FetchController();  // or AbortController() in Firefox58
var signal = controller.signal;
fetch( "/?action=upload",{ signal, observe(observer) { observer.onresponseprogress=e=>console.log(e);observer.onrequestprogress=e=>console.log(e);observer.onstatechange=n=>console.log(observer.state) }, method:"POST", body:gBlob } )

The only working observer is state in my Firefox(55/58 Ubuntu)

**Comment by chrisdavidmills** [comment]
Hi there,

I recently updated the demo and reference pages to the new syntax:

* https://github.com/mdn/dom-examples/tree/master/abort-api
* https://developer.mozilla.org/en-US/docs/Web/API/AbortSignal
* https://developer.mozilla.org/en-US/docs/Web/API/AbortController

As far as I am aware, the observer functionality is not implemented right now. The standardization has stalled on that feature, and the spec folks are not sure when/if it will get sorted out.
